{% set name = "semi-ate-control-app" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/semi-ate-control-app-{{ version }}.tar.gz
  sha256: bb715b0cfd82ecdc4c98cb06b611d7b7c836ed7339f7a4bb89e82ded08ca1565

build:
  number: 0
  noarch: python
  entry_points:
    - launch_control=ate_control_app.launch_control:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.8
    - python
  run:
    - python >=3.8
    - semi-ate-apps-common
    - semi-ate-common
    - transitions

test:
  imports:
    - ate_control_app
  commands:
    - pip check
    - launch_control --help
  requires:
    - pip

about:
  home: https://pypi.org/project/semi-ate-control-app/
  summary: Semi-ATE Control APP that steers the individual test applications in an ATE test environment.
  license: GPL-2.0-only
  license_file: ate_control_app/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
