{% set name = "semi-ate-control-app" %}
{% set version = "1.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semi-ate-control-app-{{ version }}.tar.gz
  sha256: e5368f2eaa9cd40127619a98dd8e307f9a3b78be005e7640a0c9a5755d0156b8

build:
  number: 1
  noarch: python
  entry_points:
    - launch_control=ate_control_app.launch_control:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=3.8
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - semi-ate-apps-common
    - semi-ate-common
    - transitions

test:
  imports:
    - ate_control_app
  commands:
    - pip check
    - launch_control --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/semi-ate-control-app/
  summary: Semi-ATE Control APP that steers the individual test applications in an ATE test environment.
  license: GPL-2.0-only
  license_file: ate_control_app/LICENSE.txt

extra:
  recipe-maintainers:
    - nerohmot
    - heli2src
    - Zlin526F
